version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PG_USER=superuser
      - PG_PASSWORD=secret
      - PG_DATABASE=duties
      - PG_HOST=pg
      - PG_PORT=5432
      - PORT=8080
  pg:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=duties
    volumes:
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql